### ISSUE TITLE
How to disable unix path translation?

### ISSUE THREAD

**Issue by realyukii** [msys2/Cygwin#229]
some program like `msiexec.exe` only understand Windows path, thus it cause trouble when python program tried to spawn `msiexec.exe`:

```
Unpacking msi files...
Traceback (most recent call last):
  File "/home/ACER/portable-msvc.py", line 285, in <module>
    subprocess.check_call(["msiexec.exe", "/a", m, "/quiet", "/qn", f"TARGETDIR={OUTPUT.resolve()}"])
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msiexec.exe', '/a', PosixPath('downloads/Universal CRT Headers Libraries and Sources-x86_en-us.msi'), '/quiet', '/qn', 'TARGETDIR=/home/ACER/msvc']' returned non-zero exit status 103.
```

I have tried [this solution](https://stackoverflow.com/a/34386471/22382954), but it just show another error that I'm not sure that I fully understand the error:
```
Unpacking msi files...
This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.
Traceback (most recent call last):
  File "/home/ACER/portable-msvc.py", line 285, in <module>
    subprocess.check_call(["msiexec.exe", "/a", m, "/quiet", "/qn", f"TARGETDIR={OUTPUT.resolve()}"])
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msiexec.exe', '/a', PosixPath('downloads/Universal CRT Headers Libraries and Sources-x86_en-us.msi'), '/quiet', '/qn', 'TARGETDIR=/home/ACER/msvc']' returned non-zero exit status 83.
```

**Comment by realyukii** [comment]
the python program originated from [this gist](https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977?permalink_comment_id=5246343#gistcomment-5246343)

**Comment by Biswa96** [comment]
This may help https://www.msys2.org/docs/filesystem-paths/

**Comment by realyukii** [comment]
I'm not sure if that link would help, I already tried what mentioned there but it still translate the path with `PosixPath`

**Comment by dscho** [comment]
@Biswa96 that page does not describe the new [`MSYS_NO_PATHCONV` variable](https://github.com/msys2/msys2-runtime/commit/e1db14849f307053cf0728f385fd8e2c884b4d03), maybe it should? It does not allow for as fine-grained configuration as `MSYS2_ENV_CONV_EXCL`/`MSYS2_ARG_CONV_EXCL`, but on the upside it is much, much easier to use.

**Comment by dscho** [comment]
> I'm not sure if that link would help, I already tried what mentioned there but it still translate the path with `PosixPath`

Maybe you can provide some sort of detail, such as a small reproducer, detailed output, etc? It is hard to solve a problem when forced to guess.

**Comment by realyukii** [comment]
> > I'm not sure if that link would help, I already tried what mentioned there but it still translate the path with `PosixPath`
> 
> Maybe you can provide some sort of detail, such as a small reproducer, detailed output, etc? It is hard to solve a problem when forced to guess.

Well... I do apologize for not provide enough details explicitly, here's the way to reproduce the issue:
```
pacman -S python libopenssl
curl -LOJ https://gist.githubusercontent.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977/raw/9f8555326867d4ecba70ee07f105f159f5d8afd5/portable-msvc.py
python portable-msvc.py
```

**Comment by dscho** [comment]
> curl -LOJ https://gist.githubusercontent.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977/raw/9f8555326867d4ecba70ee07f105f159f5d8afd5/portable-msvc.py

@RealYukiSan are you really calling this a _small_ reproducer?

Please revisit https://stackoverflow.com/help/mcve, in particular this part:

> Your code examples should be…
>
> * Minimal: Use as little code as possible that still produces the same problem

Also, you may want to zone in on the `PosixPath()` function, which is not even in your reproducer (probably only via yet a different asset that makes the reproducer even _less_ minimal). I bet that the use of `PosixPath()` is the problem, as you clearly want to use this on Windows and hence might need Windows paths, not POSIX paths?

**Comment by realyukii** [comment]
> are you really calling this a small reproducer?
> which is not even in your reproducer

I can't reproduce in a small reproducer, the problem is I don't even know why the `PosixPath` function was printed on CalledProcessError stack, it's not even called in the python script

> as you clearly want to use this on Windows and hence might need Windows paths, not POSIX paths?

indeed, maybe I should post the issue on [msys2-package](https://github.com/msys2/MSYS2-packages) repository instead? as it's related to specific python package installed from msys

**Comment by dscho** [comment]
> maybe I should post the issue on [msys2-package](https://github.com/msys2/MSYS2-packages) repository instead?

I don't think that it is a good idea to reflexively try to throw this issue over the wall, without even analyzing it properly yourself.

I mean, you know where in the script it is stuck, and it's likely around [this line](https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977/#file-portable-msvc-py-L285), and you could then call _that_ command individually (and have a much, much more minimal reproducer already).

Then dig into what this `.msi` does, where it is defined, where that `PosixPath()` function is used within that definition. The dig deeper. And deeper.

It's really good idea to ask people for help _after_ doing these first steps and being able to present a much more concise problem description. Otherwise, those exact people who could help you, like me, may decide that they do not want to deal with the problem altogether because _all_ the analysis is expected from them.

**Comment by realyukii** [comment]
You're right, and I do apologize for not having searched more carefully. I'm grateful for your prompt response and your civility in the face of my impatience!

I will try to debug the issue and provide any details if I found something useful to share.

**Comment by Zsar** [comment]
[Possibly related](https://github.com/msys2/MSYS2-packages/issues/5123#issuecomment-2583092106): The documented environment variables seem to have no effect in a fresh MSYS2 installation from last thursday.
